name: Auto Scraping Mobile JKN

on:
  schedule:
    - cron: '0 0 1 */6 *'  # Otomatis setiap 6 bulan (1 Jan & 1 Jul)
  workflow_dispatch:         # Bisa dijalankan manual kapanpun

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements_scraping.txt

      - name: Jalankan scraping
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scraping.py
